"""Synthetic field generators.

Why this module exists: ``docs/dataset.md`` still has every resolution box
unticked and no dataset is confirmed, so the downscaling baseline, the metrics
and the lifecycle state machine would otherwise be blocked behind Aravinth's
data work. Everything here is deterministic and needs nobody.

These generators are for **testing and interface development only**. A field
produced here is not evidence about any real event, and nothing generated by this
module may be presented as a model result — see the integrity rule in
``team/README.md``. Outputs carry ``attrs["synthetic"] = True`` so a figure or a
metric table built from one is traceable back to its origin.

Units: precipitation-like fields default to ``mm/24h`` to match the footprint
fixtures, so a synthetic peak can be compared with the numbers already in
``data/samples/``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from src.shared.fields import GriddedField

SYNTHETIC_MARKER = "synthetic"


def grid(
    lat_range: tuple[float, float],
    lon_range: tuple[float, float],
    resolution_deg: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Build ascending coordinate axes at a fixed spacing.

    The final point is excluded when the range is not an exact multiple of the
    spacing, so the spacing is always exactly ``resolution_deg`` rather than
    being stretched to fit the last point.
    """
    if resolution_deg <= 0:
        raise ValueError("resolution_deg must be positive")
    latitude = np.arange(lat_range[0], lat_range[1] + resolution_deg / 2, resolution_deg)
    longitude = np.arange(lon_range[0], lon_range[1] + resolution_deg / 2, resolution_deg)
    return np.round(latitude, 10), np.round(longitude, 10)


def _mesh(latitude: np.ndarray, longitude: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    return np.meshgrid(longitude, latitude)


def _rankine_bump(
    distance: np.ndarray,
    amplitude: float,
    radius_deg: float,
    core_fraction: float,
) -> np.ndarray:
    """A bump with a flat core and a smooth falloff, in [0, amplitude].

    A core fraction of 0 gives a plain Gaussian; a larger core produces the
    flat-topped profile that makes peak preservation measurable, because a
    smoothed version of it still has *a* maximum, just not the right one.
    """
    inner = max(core_fraction * radius_deg, 1e-9)
    profile = np.exp(-0.5 * (np.maximum(distance - inner, 0.0) / radius_deg) ** 2)
    return amplitude * profile


def gaussian_bump(
    latitude: np.ndarray,
    longitude: np.ndarray,
    *,
    centre: tuple[float, float],
    amplitude: float,
    radius_deg: float,
    core_fraction: float = 0.0,
    name: str = "synthetic_bump",
    units: str | None = "mm/24h",
) -> GriddedField:
    """A single localized anomaly. The building block for every other generator."""
    grid_lon, grid_lat = _mesh(latitude, longitude)
    dlat = grid_lat - centre[0]
    # Longitude distance ignores the dateline, consistent with GriddedField's
    # documented single-world assumption.
    dlon = (grid_lon - centre[1]) * np.cos(np.radians(centre[0]))
    distance = np.sqrt(dlat**2 + dlon**2)
    values = _rankine_bump(distance, amplitude, radius_deg, core_fraction)
    return GriddedField(
        values=values,
        latitude=latitude,
        longitude=longitude,
        name=name,
        units=units,
        attrs={"synthetic": True, "generator": "gaussian_bump"},
    )


def sharp_peak_field(
    *,
    lat_range: tuple[float, float] = (8.0, 18.0),
    lon_range: tuple[float, float] = (75.0, 85.0),
    resolution_deg: float = 0.05,
    centre: tuple[float, float] = (13.08, 80.27),
    amplitude: float = 84.2,
    radius_deg: float = 0.18,
    core_fraction: float = 0.35,
) -> GriddedField:
    """A fine-resolution reference field containing a sharp, flat-topped extreme.

    This is the "truth" in the extreme-preservation tests. Its peak sits at a
    known location with a small radius, so upsampling from a coarse grid cannot
    reproduce it without genuinely resolving it. The default amplitude of
    84.2 mm/24h matches ``data/samples/footprints.json``, so a synthetic metric
    table is directly comparable to the fixture the dashboard already renders.
    """
    latitude, longitude = grid(lat_range, lon_range, resolution_deg)
    field = gaussian_bump(
        latitude,
        longitude,
        centre=centre,
        amplitude=amplitude,
        radius_deg=radius_deg,
        core_fraction=core_fraction,
        name="synthetic_reference",
    )
    field.attrs["generator"] = "sharp_peak_field"
    return field


def smoothed_field(
    reference: GriddedField,
    *,
    radius_deg: float = 0.9,
    amplitude_factor: float = 0.62,
    name: str = "synthetic_smoothed",
) -> GriddedField:
    """A deliberately under-resolved version of ``reference``.

    Standing in for a predictive model that smooths extremes away: the peak is
    lower and broader than the truth. This is the **known-failure case** the
    metrics must catch — if a metric table reports good scores for this field,
    the metric is wrong, not the field.
    """
    peak = reference.peak
    if peak is None:
        raise ValueError("reference field has no finite values")
    latitude, longitude = reference.latitude, reference.longitude
    index_lat, index_lon = np.unravel_index(
        int(np.nanargmax(reference.values)), reference.values.shape
    )
    centre = (float(latitude[index_lat]), float(longitude[index_lon]))

    grid_lon, grid_lat = _mesh(latitude, longitude)
    dlat = grid_lat - centre[0]
    dlon = (grid_lon - centre[1]) * np.cos(np.radians(centre[0]))
    distance = np.sqrt(dlat**2 + dlon**2)
    values = _rankine_bump(distance, peak * amplitude_factor, radius_deg, 0.0)

    return GriddedField(
        values=values,
        latitude=latitude,
        longitude=longitude,
        name=name,
        units=reference.units,
        attrs={"synthetic": True, "generator": "smoothed_field"},
    )


def random_field(
    latitude: np.ndarray,
    longitude: np.ndarray,
    *,
    seed: int,
    amplitude: float = 10.0,
    correlation_deg: float = 1.0,
    name: str = "synthetic_noise",
    units: str | None = "mm/24h",
) -> GriddedField:
    """Smooth random noise, for a component that must not be mistaken for structure.

    Uses a seeded generator so a failure is reproducible, and smooths the noise
    so it is not just white noise that any detector would trivially reject.
    """
    rng = np.random.default_rng(seed)
    grid_lon, grid_lat = _mesh(latitude, longitude)
    values = np.zeros_like(grid_lat)
    for _ in range(48):
        centre_lat = float(rng.uniform(latitude.min(), latitude.max()))
        centre_lon = float(rng.uniform(longitude.min(), longitude.max()))
        dlat = grid_lat - centre_lat
        dlon = (grid_lon - centre_lon) * np.cos(np.radians(centre_lat))
        distance = np.sqrt(dlat**2 + dlon**2)
        values += rng.normal() * _rankine_bump(distance, amplitude, correlation_deg, 0.0)
    values -= values.min()
    return GriddedField(
        values=values,
        latitude=latitude,
        longitude=longitude,
        name=name,
        units=units,
        attrs={"synthetic": True, "generator": "random_field", "seed": seed},
    )


@dataclass
class SyntheticEvent:
    """One time step of a synthetic event, with the truth it was built from."""

    step: int
    hours_after_start: float
    field: GriddedField
    centre: tuple[float, float]
    amplitude: float


def translating_event(
    *,
    steps: int = 6,
    step_hours: float = 6.0,
    start_centre: tuple[float, float] = (11.0, 78.5),
    travel_deg_per_step: tuple[float, float] = (0.35, 0.62),
    start_amplitude: float = 24.0,
    peak_amplitude: float = 78.0,
    peak_step: int = 3,
    radius_deg: float = 0.7,
    core_fraction: float = 0.3,
    lat_range: tuple[float, float] = (8.0, 16.0),
    lon_range: tuple[float, float] = (76.0, 86.0),
    resolution_deg: float = 0.1,
    name: str = "synthetic_event",
) -> list[SyntheticEvent]:
    """A storm that translates and intensifies, then weakens.

    Intensity rises linearly to ``peak_step`` and falls after it, and the centroid
    moves a fixed distance per step. That gives the lifecycle state machine a
    history with a known answer: the phase at ``peak_step`` must be PEAK, before
    it must be intensifying or expanding, and after it must be DECAY.

    ``start_centre`` and the travel vector are chosen so the event is still fully
    inside the default grid at every step — an event that walks off the domain
    would make peak-preservation comparisons meaningless.
    """
    if steps < 3:
        raise ValueError("need at least 3 steps to have a pre-peak and post-peak phase")
    if not 0 < peak_step < steps - 1:
        raise ValueError("peak_step must leave at least one step on each side")

    latitude, longitude = grid(lat_range, lon_range, resolution_deg)
    events: list[SyntheticEvent] = []
    for step in range(steps):
        fraction = step / peak_step if step <= peak_step else (steps - 1 - step) / (
            steps - 1 - peak_step
        )
        amplitude = start_amplitude + (peak_amplitude - start_amplitude) * fraction
        centre = (
            round(start_centre[0] + travel_deg_per_step[0] * step, 6),
            round(start_centre[1] + travel_deg_per_step[1] * step, 6),
        )
        field = gaussian_bump(
            latitude,
            longitude,
            centre=centre,
            amplitude=amplitude,
            radius_deg=radius_deg,
            core_fraction=core_fraction,
            name=f"{name}_t{step}",
        )
        field.attrs["generator"] = "translating_event"
        events.append(
            SyntheticEvent(
                step=step,
                hours_after_start=step * step_hours,
                field=field,
                centre=centre,
                amplitude=amplitude,
            )
        )
    return events


def metrics_of(field: GriddedField) -> dict[str, Any]:
    """Small summary used by tests and debug output. Not a validation metric."""
    return {
        "name": field.name,
        "shape": field.shape,
        "resolution_deg": field.resolution_deg(),
        "peak": field.peak,
        "units": field.units,
        "synthetic": field.attrs.get(SYNTHETIC_MARKER, False),
    }
