"""
VARNIKA — Stage 6: Interface export

Defines and produces the actual handoff artifact between the GNN/spatio-
temporal stage (Varnika) and the Threat Object / tracker (Sachin +
Navaneedan) and precursor stage (Hariharan), per the pipeline table in the
team plan (Stage 4 GNN -> Stage 5 Tracking / Stage 6 Precursors).

Contract (documented here so all three of you can code against it without
waiting on each other):

{
  "timestep": int,
  "nodes": [
    {
      "node_id": int,
      "latitude": float,
      "longitude": float,
      "raw_features": {"temperature":.., "pressure":.., "humidity":..,
                        "wind_speed":.., "precipitation":..},
      "predicted_next_features": {...same keys...},   # from the model, one step ahead
      "threat_embedding": [float, ...]                 # fixed-length vector;
                                                         # currently the un-trained
                                                         # baseline's smoothed state,
                                                         # replaced by decoder_embedding
                                                         # once 05_st_gnn_model.py is trained
    },
    ...
  ]
}

This uses the numpy baseline's outputs (real numbers, computed today).
Swap in the trained GNN's `threat_embedding` output once available -- the
schema does not need to change.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
REPO_ROOT = BASE_DIR.parent.parent
OUT_DIR = BASE_DIR / "outputs"


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    nodes = pd.read_csv(OUT_DIR / "node_table.csv")
    tensor = np.load(OUT_DIR / "st_tensor.npy")                          # raw units (T,N,F)
    
    # Use real trained GNN predictions and embeddings if available
    has_gnn_preds = (OUT_DIR / "gnn_predictions.npy").exists()
    has_gnn_embs = (OUT_DIR / "threat_embeddings.npy").exists()

    if has_gnn_preds:
        preds_phys = np.load(OUT_DIR / "gnn_predictions.npy")
    else:
        preds_norm = np.load(OUT_DIR / "baseline_predictions_normalised.npy")
        mu = np.load(OUT_DIR / "norm_mu.npy")
        sigma = np.load(OUT_DIR / "norm_sigma.npy")
        preds_phys = preds_norm * sigma + mu

    if has_gnn_embs:
        embeddings = np.load(OUT_DIR / "threat_embeddings.npy")
    else:
        embeddings = None

    with open(OUT_DIR / "feature_order.txt") as f:
        feature_names = f.read().splitlines()

    # Export one representative timestep (the peak event from stage 4)
    example_t = 25  # matches the peak timestep found in 04_historical_event_replay.py
    pred_idx = example_t - 1

    record = {"timestep": example_t, "nodes": []}
    for _, row in nodes.iterrows():
        nid = int(row["node_id"])
        raw = tensor[example_t, nid, :]
        pred_raw = preds_phys[pred_idx, nid, :]

        if has_gnn_embs and embeddings is not None:
            node_emb = [round(float(v), 4) for v in embeddings[pred_idx, nid, :]]
        else:
            node_emb = [round(float(v), 4) for v in pred_raw]

        record["nodes"].append({
            "node_id": nid,
            "latitude": float(row["latitude"]),
            "longitude": float(row["longitude"]),
            "raw_features": {name: round(float(v), 4) for name, v in zip(feature_names, raw)},
            "predicted_next_features": {name: round(float(v), 4) for name, v in zip(feature_names, pred_raw)},
            "threat_embedding": node_emb,
        })

    with open(OUT_DIR / "interface_export_example.json", "w") as f:
        json.dump(record, f, indent=2)

    schema_doc = {
        "description": "Contract between Varnika's spatio-temporal stage and "
                        "Sachin's tracker / Hariharan's precursor stage.",
        "fields": {
            "timestep": "sequential hourly index into the shared grid record",
            "nodes[].node_id": "0..65, fixed by 01_graph_construction.py node_table.csv",
            "nodes[].raw_features": "actual observed grid values at this timestep",
            "nodes[].predicted_next_features": "one-step-ahead prediction for this node",
            "nodes[].threat_embedding": "16-dimensional latent representation generated by the trained ST-GNN",
        },
    }
    with open(OUT_DIR / "interface_schema.json", "w") as f:
        json.dump(schema_doc, f, indent=2)

    print(f"Wrote example export for timestep {example_t} -> "
          f"{OUT_DIR / 'interface_export_example.json'}")
    print(f"Wrote schema doc -> {OUT_DIR / 'interface_schema.json'}")


if __name__ == "__main__":
    main()

